{{/*
GetSecretKeyValue gets the value of a key from within a specified Secret.
Usage: {{ getSecretKeyValue "existingSecretName" "keyName" "namespace" }}
*/}}
{{- define "getSecretKeyValue" -}}
{{- $secretName := index . 0 -}}
{{- $keyName := index . 1 -}}
{{- $namespace := index . 2 -}}
{{- $secret := (lookup "v1" "Secret" $namespace $secretName) -}}
{{- if $secret -}}
  {{- $value := index $secret.data $keyName -}}
  {{- if $value -}}
    {{- $decodedValue := $value | b64dec -}}
    {{- print $decodedValue -}}
  {{- else -}}
    {{- fail (printf "Error: Key %s not found in the secret %s in namespace %s" $keyName $secretName $namespace) -}}
  {{- end -}}
{{- else -}}
  {{- fail (printf "Error: Secret %s not found in namespace %s" $secretName $namespace) -}}
{{- end -}}
{{- end -}}
