{{ $image := "linuxserver/openssh-server:latest" }}

apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    run: {{ .Release.Name }}-process
  name: {{ .Release.Name }}-process
  namespace: {{ .Values.skaha.namespace }}
spec:
  replicas: {{ default 1 .Values.replicaCount }}
  selector:
    matchLabels:
      run: {{ .Release.Name }}-process
  template:
    metadata:
      creationTimestamp: null
      labels:
        run: {{ .Release.Name }}-process
    spec:
      initContainers:
      - name: backup-original-passwd-groups
        image: {{ .Values.deployment.sshd.image | default $image }}
        command: ["/bin/sh", "-c", "cp /etc/passwd /etc-passwd/passwd-orig && cp /etc/group /etc-group/group-orig"]
        volumeMounts:
        - mountPath: "/etc-passwd"
          name: etc-passwd
        - mountPath: "/etc-group"
          name: etc-group
        securityContext:
          runAsUser: 0
          runAsGroup: 0
      - name: init-users-groups
        image: {{ .Values.deployment.sshd.image | default $image }}
        imagePullPolicy: Always
        command: ["/init-users-groups/init-users-groups-from-service.sh"]
        env:
        - name: POSIX_MAPPER_URI
          value: {{ .Values.deployment.sshd.posixMapperResourceID | required "value for .Values.deployment.sshd.posixMapperResourceID is required." }}
        - name: REGISTRY_URL
          value: {{ .Values.deployment.sshd.registryURL }}
        volumeMounts:
        - mountPath: "/etc-passwd"
          name: etc-passwd
        - mountPath: "/etc-group"
          name: etc-group
        - mountPath: "/init-users-groups"
          name: init-users-groups
        - mountPath: "/config/keys"
          name: posix-mapper-api-secret
          readOnly: true
        securityContext:
          runAsUser: 0
          runAsGroup: 0
      containers:
      - image: {{ .Values.deployment.sshd.image | default $image }}
        imagePullPolicy: Always
        name: {{ .Release.Name }}-process
        env:
        - name: USER_NAME
          value: root
        - name: POSIX_MAPPER_URI
          value: {{ .Values.deployment.sshd.posixMapperResourceID }}
        - name: REGISTRY_URL
          value: {{ .Values.deployment.sshd.registryURL }}
        ports:
        - containerPort: 2222
          protocol: TCP
        resources:
          requests:
            memory: {{ .Values.deployment.sshd.resources.requests.memory }}
            cpu: {{ .Values.deployment.sshd.resources.requests.cpu }}
          limits:
            memory: {{ .Values.deployment.sshd.resources.limits.memory }}
            cpu: {{ .Values.deployment.sshd.resources.limits.cpu }}
        {{- with .Values.deployment.sshd.extraEnv }}
        env:
        {{- toYaml . | nindent 8 }}
        {{- end }}
        ports:
        - containerPort: 2222
          protocol: TCP
        volumeMounts: 
        - mountPath: "/config/keys"
          name: posix-mapper-api-secret
          readOnly: true
        # Maintain the 'etc-passwd' and 'etc-group' mappings for the init-users-groups script to
        # periodically run.
        - mountPath: "/etc-passwd"
          name: etc-passwd
        - mountPath: "/etc-group"
          name: etc-group
        - mountPath: "/etc/periodic/15min"
          name: init-users-groups
        - mountPath: "/etc/passwd"
          name: etc-passwd
          subPath: passwd
        - mountPath: "/etc/group"
          name: etc-group
          subPath: group
        - mountPath: "/home"
          name: cavern-volume
          subPath: "{{ .Values.deployment.sshd.filesystem.subPath | default "" }}/home"
        {{- with .Values.deployment.sshd.extraVolumeMounts }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      securityContext:
        runAsUser: 0
        runAsGroup: 0
      volumes:
      - name: init-users-groups
        configMap:
          name: {{ .Release.Name}}-init-users-groups-config
          defaultMode: 0777
      - name: posix-mapper-api-secret
        secret:
          defaultMode: 420
          secretName: posix-mapper-api-secret
      - name: etc-group
        emptyDir: {}
      - name: etc-passwd
        emptyDir: {}
      - name: cavern-volume
        {{- toYaml .Values.storage.service.spec | nindent 8 }}
      {{- with .Values.deployment.sshd.extraVolumes }}
      {{- toYaml . | nindent 6 }}
      {{- end }}
