apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.skahaWorkload.namespace }}-cavern-pvc
  namespace: {{ .Values.skahaWorkload.namespace }}
  annotations:
    "helm.sh/resource-policy": keep
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
  {{- if not (eq .Values.storage.sessions.claim.storageClassName nil) }}
  storageClassName: ""
  {{- end }}
  selector:
    matchLabels:
{{- toYaml .Values.storage.sessions.claim.labels | nindent 6 }}
