FROM python:2.7-slim

WORKDIR /usr/src/app

RUN pip install --upgrade pip

RUN pip install cachetools && \
    mock && \
    pytest

COPY entrypoint.sh /entrypoint.sh

RUN chmod +x /entrypoint.sh

ENTRYPOINT ["/entrypoint.sh"]
