kubernetesClusterDomain: cluster.local

# Tell Kubernetes to spin up multiple instances.  Defaults to 1.
replicaCount: 1

# It's best to keep these set as such, unless you're willing to change these in several places.
skaha:
  namespace: skaha-system

# POSIX Mapper web service deployment
deployment:
  hostname: example.host.com    # Change this!
  sciencePortal:
    image: images.opencadc.org/platform/science-portal:0.2.2
    imagePullPolicy: Always

    # Optionally set the DEBUG port.
    # extraEnv:
    # - name: CATALINA_OPTS
    #   value: "-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=0.0.0.0:5555"
    # - name: JAVA_OPTS
    #   value: "-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=0.0.0.0:5555"

    # Uncomment to debug.  Requires options above as well as service port exposure below.
    # extraPorts:
    # - containerPort: 5555
    #   protocol: TCP

    # Resources provided to the Skaha service.
    resources:
      requests:
        memory: "500M"
        cpu: "500m"
      limits:
        memory: "500M"
        cpu: "500m"

    # The Resource ID of the Service that contains the URL of the Skaha service in the IVOA Registry
    skahaResourceID: ivo://example.org/skaha

    # ID (URI) of the GMS Service.
    gmsID: ivo://skao.int/gms

    # OIDC (IAM) server configuration.  These are required
    # oidc:
      # Location of the OpenID Provider (OIdP)
      # uri: https://ska-iam.stfc.ac.uk/
      # The Client ID as listed on the OIdP.
      # clientID: 
      # The Client Secret, which should be generated by the OIdP.
      # clientSecret: 
      # Name of existing secret containing 'clientSecret' key with value of Client Secret, which should be generated by the OIdP.
      # This is an alternative to providing the 'clientSecret' in cleartext in the chart.
      # existingSecretName:
      # Where the OIdP should send the User after successful authentication (redirect_uri)
      # redirectURI:
      # Where to redirect to after the redirectURI callback has completed.  This will usually be the URL to the /science-portal main page.
      # callbackURI: 
      # The standard OpenID scopes for token requests.  This is required.
      # scope: "openid profile offline_access"

    registryURL: https://spsrc27.iaa.csic.es/reg

    # The IdentityManager class handling authentication.  This should generally be left alone
    identityManagerClass: org.opencadc.auth.StandardIdentityManager

    # Optionally mount a custom CA certificate
    # extraVolumeMounts:
    # - mountPath: "/config/cacerts"
    #   name: cacert-volume

    # Create the CA certificate volume to be mounted in extraVolumeMounts
    # extraVolumes:
    # - name: cacert-volume
    #   secret:
    #     defaultMode: 420
    #     secretName: science-portal-cacert-secret

    # Supported theme name (src or canfar).
    themeName: src

# secrets:
  # Uncomment to enable local or self-signed CA certificates for your domain to be trusted.
  # science-portal-cacert-secret:
  #   ca.crt: <base64 encoded ca crt>

# For the token caching
redis:
  architecture: 'standalone'
  auth:
    enabled: false
