---
apiVersion: batch/v1
kind: Job
metadata:
  name: "skaha-add-project"
spec:
  ttlSecondsAfterFinished: 3600
  backoffLimit: 0
  template:
    spec:
      restartPolicy: Never
      securityContext:
        seccompProfile:
          type: RuntimeDefault
      containers:
      - name: "skaha-add-project"
        image: images.canfar.net/skaha-system/add-project:1.3
        imagePullPolicy: Always
        # TODO: automate the setting of this in the calling script
        command: ["/usr/bin/add-project"]
        # args: project-name, owner-uid, project-group-gid, read-only or read-write, quota-in-gb, project-base-dir
        args: ["project-name", "owner-uid", "project-gid", "project-permission", "project-quota-gb", "project-base-dir"]
        volumeMounts:
        - mountPath: "/cavern"
          name: cavern-volume
          subPath: cavern
        securityContext:
          runAsUser: 0
          allowPrivilegeEscalation: false
      serviceAccountName: skaha
      volumes:
      - name: cavern-volume
        cephfs:
          monitors:
          - 10.30.201.3:6789
          - 10.30.202.3:6789
          - 10.30.203.3:6789
          path: /volumes/_nogroup/dcd994bc-c0d4-4557-9fbf-28fc4ef5969e
          user: keel-dev-admin
          secretRef:
            name: cephfs-cephx-admin-key
          readOnly: false
