{{- range $secretIndex, $secretName := .Values.secrets }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ $secretIndex }}
  namespace: {{ $.Release.Namespace }}
type: Opaque
data:
  {{- range $certKey, $certValue := . }}
    {{ $certKey }}: {{ $certValue | quote }}
  {{- end }}
{{- end }}

---
{{- $posixMapperAPISecretName := "posix-mapper-api-keys" -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $posixMapperAPISecretName }}
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
{{- range $clientIndex, $clientName := .Values.deployment.posixMapper.authorizedClients }}
  {{- include "gen.secret" (dict "clientName" $clientName "namespace" $.Release.Namespace "secretName" $posixMapperAPISecretName) -}}
{{- end }}
