#!/bin/bash

set -e

### Give the SSSD container time to initialize
sleep 10

SELF=add-user
CONFDIR=/add-user-config

TS=$(date)
echo "$TS $SELF START"

if [ -z "$3" ]
  then
    echo "Usage: add-user <username> <uid> <quota in GB> <absolute path to user home dir>"
    exit 2
fi

USERNAME=$1
USERID=$2
QUOTA=$3
HOMEDIR=$4

BASHRC="$CONFDIR/bashrc"
XRESOURCES="$CONFDIR/Xresources"
CASACONFIG="$CONFDIR/casa-config.tar"
CERTFILE="/root/.ssl/cadcproxy.pem"

if [ ! -f $CASACONFIG ]
  then
    echo "No file casa-config.tar found in $CONFDIR"
    exit  2
fi

if [ ! -f $BASHRC ]
  then
    echo "No file .bashrc found in $CONFDIR"
    exit  2
fi

if [ ! -f $XRESOURCES ]
  then
    echo "No file .Xresources found in $CONFDIR"
    exit  2
fi

echo "  Certfile: $CERTFILE"
echo "Creating allocation for $USERNAME"
echo -n "  Creating home dir $HOMEDIR..."
mkdir -p $HOMEDIR
chown $USERID:$USERID $HOMEDIR
chmod 700 $HOMEDIR
echo " Creating allocation for $USERNAME: OK"

echo -n "  Adding home dir config files..."
cp $BASHRC $HOMEDIR/.bashrc
chown $USERID:$USERID $HOMEDIR/.bashrc
cp $XRESOURCES $HOMEDIR/.Xresources
chown $USERID:$USERID $HOMEDIR/.Xresources
# xrdb is run on .Xresources later to load the config
echo " Adding home dir config files: OK"

echo -n "  Creating home .ssl directory..."
mkdir $HOMEDIR/.ssl
chown $USERID:$USERID $HOMEDIR/.ssl
echo " Creating home .ssl directory: OK"

echo -n "  Adding CASA configuration..."
mkdir $HOMEDIR/.casa
cp $CASACONFIG $HOMEDIR/.casa/
cd $HOMEDIR/.casa
tar xf casa-config.tar
rm casa-config.tar
chown -R $USERID:$USERID $HOMEDIR/.casa
echo " Adding CASA configuration: OK"

echo -n "  Setting user quota to ${QUOTA}G..."

# Ignore the errors from the CephFS xattr in case they're not supported.
setfattr -n ceph.quota.max_bytes -v ${QUOTA}000000000 $HOMEDIR 2> /dev/null
STAT=${?}

if [[ ! "X${STAT}" == "X0" ]]; then
  echo "No CephFS extended attribute plugin found.  Skipping..."
fi

setfattr -n user.ivo://ivoa.net/vospace/core#quota -v ${QUOTA}000000000 $HOMEDIR
echo " Setting user quota to ${QUOTA}G: OK"

TS=$(date)
echo "$TS $SELF DONE"
