{{- if .Values.rbac.create }}
{{- $queues := include "metrics-api.clusterQueues" . | trim | fromJsonArray }}
{{- $namespaces := include "metrics-api.kueueNamespaces" . | trim | fromJsonArray }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "metrics-api.fullnameWithSuffix" (dict "context" . "suffix" "kueue-read") }}
  labels:
    {{- include "metrics-api.labels" . | nindent 4 }}
rules:
  - apiGroups: ["kueue.x-k8s.io"]
    resources: ["clusterqueues"]
    resourceNames:
{{- range $queue := $queues }}
      - {{ $queue | quote }}
{{- end }}
    verbs: ["get"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "metrics-api.fullnameWithSuffix" (dict "context" . "suffix" "kueue-read") }}
  labels:
    {{- include "metrics-api.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "metrics-api.fullnameWithSuffix" (dict "context" . "suffix" "kueue-read") }}
subjects:
  - kind: ServiceAccount
    name: {{ include "metrics-api.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
{{- range $namespace := $namespaces }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "metrics-api.fullnameWithSuffix" (dict "context" $ "suffix" "localqueue-read") }}
  namespace: {{ $namespace }}
  labels:
    {{- include "metrics-api.labels" $ | nindent 4 }}
rules:
  - apiGroups: ["kueue.x-k8s.io"]
    resources: ["localqueues"]
    verbs: ["list"]
  - apiGroups: ["batch"]
    resources: ["jobs"]
    verbs: ["get", "list"]
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "list"]
  - apiGroups: ["metrics.k8s.io"]
    resources: ["pods"]
    verbs: ["get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "metrics-api.fullnameWithSuffix" (dict "context" $ "suffix" "localqueue-read") }}
  namespace: {{ $namespace }}
  labels:
    {{- include "metrics-api.labels" $ | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "metrics-api.fullnameWithSuffix" (dict "context" $ "suffix" "localqueue-read") }}
subjects:
  - kind: ServiceAccount
    name: {{ include "metrics-api.serviceAccountName" $ }}
    namespace: {{ $.Release.Namespace }}
{{- end }}
{{- end }}
