apiVersion: v1
kind: Service
metadata:
  name: {{ include "metrics-api.fullnameWithSuffix" (dict "context" . "suffix" "metrics-api") }}
  labels:
    {{- include "metrics-api.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  selector:
    {{- include "metrics-api.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: api
  ports:
    - name: http
      port: 8000
      targetPort: http
      protocol: TCP
