
# Kueue setups
kueue:
  resourceFlavors:
  - name: skaha
    
  localQueues:
    skaha-workload-queue-interactive:
      namespace: skaha-workload
      clusterQueue: skaha-cluster-queue-interactive
      group: "prototyping-groups/mini-src/platform-users"
      jobType: carta,notebook,desktop,contributed,desktop-app
    skaha-workload-queue-headless:
      namespace: skaha-workload
      clusterQueue: skaha-cluster-queue-headless
      group: "prototyping-groups/mini-src/platform-users"
      jobType: headless

  clusterQueues:
    skaha-cluster-queue-interactive:
      cohort: "skaha-queue"
      resourceGroups:
      - coveredResources: ["cpu", "memory", "ephemeral-storage"]
        flavors:
        - name: skaha
          resources:
          - name: cpu
            nominalQuota: 6 # Change this according to the available resources
            borrowingLimit: 2 # Change this according to the resource requirements
          - name: memory
            nominalQuota: 6Gi # Change this according to the available resources
            borrowingLimit: 2Gi # Change this according to the available resources 
          - name: ephemeral-storage
            nominalQuota: 50Gi
    skaha-cluster-queue-headless:
      cohort: "skaha-queue"
      resourceGroups:
      - coveredResources: ["cpu", "memory", "ephemeral-storage"]
        flavors:
        - name: skaha
          resources:
          - name: cpu
            nominalQuota: 4 # Change this according to the available resources
            borrowingLimit: 0 # Change this according to the resource requirements
          - name: memory
            nominalQuota: 4Gi # Change this according to the available resources
            borrowingLimit: 0Gi # Change this according to the resource requirements
          - name: ephemeral-storage
            nominalQuota: 50Gi
