bases:
- ../../../base/skaha
namespace: skaha-system
patchesStrategicMerge:
- skaha-tomcat-deployment.yaml
- skaha-ingress.yaml
configMapGenerator:
- name: skaha-config
  behavior: merge
  files:
  - config/cadc-registry.properties
  - config/catalina.properties
  - config/k8s-resources.properties
  - config/launch-carta.yaml
  - config/launch-notebook.yaml
  - config/launch-desktop.yaml
  - config/launch-headless.yaml
  - config/launch-desktop-app.yaml
  - config/launch-contributed.yaml
  - config/service-notebook.yaml
  - config/ingress-notebook.yaml
  - config/service-desktop.yaml
  - config/ingress-desktop.yaml
  - config/service-carta.yaml
  - config/ingress-carta.yaml
  - config/service-contributed.yaml
  - config/ingress-contributed.yaml
generatorOptions:
 disableNameSuffixHash: true
