#!/bin/bash

set -e

SELF=arcade-cavern-allocate
CONFDIR=/config

TS=$(date)
echo "$TS $SELF START"

if [ -z "$1" ]
  then
    echo "Usage: arcade-cavern-allocation <userid>"
    exit 2
fi
USERID=$1

BASHRC="$CONFDIR/bashrc"
XRESOURCES="$CONFDIR/Xresources"
CASACONFIG="$CONFDIR/casa-config.tar"
CERTFILE="/root/.ssl/cadcproxy.pem"

if [ ! -f $CONFDIR/homedir ]
  then
    echo "No file homedir found in $CONFDIR"
    exit  2
fi

if [ ! -f $CONFDIR/arcadegroup ]
  then
    echo "No file arcadegroup found in $CONFDIR"
    exit  2
fi

if [ ! -f $CASACONFIG ]
  then
    echo "No file casa-config.tar found in $CONFDIR"
    exit  2
fi

if [ ! -f $CERTFILE ]
  then
    echo "No file cadcproxy.pem found in $CONFDIR"
    exit  2
fi

if [ ! -f $BASHRC ]
  then
    echo "No file .bashrc found in $CONFDIR"
    exit  2
fi

if [ ! -f $XRESOURCES ]
  then
    echo "No file .Xresources found in $CONFDIR"
    exit  2
fi

HOMEBASE=`cat $CONFDIR/homedir`
HOMEDIR="$HOMEBASE/$USERID"
ARCADEGROUP=`cat $CONFDIR/arcadegroup`

echo "  Certfile: $CERTFILE"
echo "  ARCADE Group: $ARCADEGROUP"

echo "Creating allocation for $USERID"
echo -n "  Creating home dir $HOMEDIR..."
mkdir $HOMEDIR
chown $USERID $HOMEDIR
chgrp $USERID $HOMEDIR
echo " Done"

echo -n "  Adding home dir config files..."
cp $BASHRC $HOMEDIR/.bashrc
cp $XRESOURCES $HOMEDIR/.Xresources
echo " Done"

echo -n "  Creating home .ssl directory ..."
mkdir $HOMEDIR/.ssl
echo " Done"

echo -n "  Adding CASA configuration..."
mkdir $HOMEDIR/.casa
cp $CASACONFIG $HOMEDIR/.casa/.
cd $HOMEDIR/.casa
tar xf casa-config.tar
rm casa-config.tar
echo " Done"

echo -n "  Adding user to Aracde group..."
curl -X PUT -E $CERTFILE "https://ws-cadc.canfar.net/ac/groups/$ARCADEGROUP/userMembers/$USERID?idType=http"
echo " Done"

TS=$(date)
echo "$TS $SELF DONE"
