apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-config
  namespace: {{ .Values.skaha.namespace }}
data:
{{ tpl (.Files.Glob "config/*").AsConfig . | indent 2 }}
{{- range $configFileName, $configFileValue := .Values.deployment.cavern.extraConfigData }}
{{- if $configFileName | hasSuffix ".key" }}
  {{ $configFileName }}: {{ $configFileValue | b64dec | quote }}
{{- else }}
  {{ $configFileName }}: {{ $configFileValue }}
{{- end }}
{{- end }}
