apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-config
  namespace: {{ .Values.skaha.namespace }}
data:
{{ tpl (.Files.Glob "config/*").AsConfig . | indent 2 }}
{{- include "utils.extraConfig" (dict "extraConfigData" .Values.deployment.cavern.extraConfigData) -}}
