{{ $releaseName := .Release.Name }}
{{- with required "UWS Database configuration is required." .Values.deployment.cavern.uws.db }}
{{- if .install }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ $releaseName }}-uws-postgres
  namespace: {{ $.Values.skaha.namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ $releaseName }}-uws-postgres
  template:
    metadata:
      labels:
        app: {{ $releaseName }}-uws-postgres
    spec:
      securityContext:
        runAsUser: {{ .runUID | required ".runUID is required for PostgreSQL" }}
        seccompProfile:
          type: RuntimeDefault
      containers:
        - name: postgres
          image: postgres:15
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5432  # Exposes container port
          envFrom:
            - configMapRef:
                name: {{ $releaseName }}-uws-postgres-config
          volumeMounts:
            - mountPath: /docker-entrypoint-initdb.d
              name: postgresinit
            {{- if .storage }}
            - mountPath: /var/lib/postgresql/data
              name: postgresdb
            {{- end }}
          securityContext:
            allowPrivilegeEscalation: false
      volumes:
        {{- if .storage }}
        - name: postgresdb
          {{- toYaml .storage.spec | nindent 10 }}
        {{- end }}
        - name: postgresinit
          configMap:
            name: {{ $releaseName }}-uws-postgres-init
{{- end }}
{{- end }}
