#!/bin/bash

set -e

### Give the SSSD container time to initialize

SELF=arcade-carta

TS=$(date)
echo "$TS $SELF START"

if [ "$#" -ne 2 ]; then
    echo "Usage: arcade-cavern-allocation <root> <folder>"
    exit 2
fi
ROOT=$1
FOLDER=$2
echo "root: $ROOT"
echo "folder: $FOLDER"
echo "command: /carta/CARTA-v1.3-remote/carta --folder=$FOLDER --root=$ROOT --port=5901 --fport=6901"
/carta/CARTA-v1.3-remote/carta --folder=$FOLDER --root=$ROOT --port=5901 --fport=6901
echo "Done"

### Listen to the log file until the process ends
sleep 5

PID=$(pgrep -x 'carta_backend')
echo "PID: $PID"

LOGFILE=/carta/CARTA/log/arcade-carta.log

tail --pid $PID -F $LOGFILE

TS=$(date)
echo "$TS $SELF DONE"
