apiVersion: config.kueue.x-k8s.io/v1beta2
kind: Configuration
health:
  healthProbeBindAddress: :8081
metrics:
  bindAddress: :8443
webhook:
  port: 9443
leaderElection:
  leaderElect: true
  resourceName: c1f6bfd2.kueue.x-k8s.io
controller:
  groupKindConcurrency:
    Job.batch: 5
    Workload.kueue.x-k8s.io: 10
    LocalQueue.kueue.x-k8s.io: 5
    Cohort.kueue.x-k8s.io: 1
    ClusterQueue.kueue.x-k8s.io: 5
    ResourceFlavor.kueue.x-k8s.io: 1
clientConnection:
  qps: 300
  burst: 500
integrations:
  frameworks:
    - batch/job
admissionFairSharing:
  usageHalfLifeTime: 1m
  usageSamplingInterval: 1s
  resourceWeights:
    cpu: 1
    memory: 1
