 {{- if .Values.kueue }}
{{ range $queue, $config := .Values.kueue.localQueues }}
apiVersion: kueue.x-k8s.io/v1beta1
kind: LocalQueue
metadata:
  namespace: {{ $config.namespace }}
  name: {{ $queue }}
spec:
  clusterQueue: {{ $config.clusterQueue }}
---
{{ end }}
{{- end }}