 {{- if .Values.kueue }}
{{ range $queue, $config := .Values.kueue.clusterQueues }}
apiVersion: kueue.x-k8s.io/v1beta1
kind: ClusterQueue
metadata:
  name: "{{ $queue }}"
spec:
  namespaceSelector: {} # match all.
  {{ if $config.cohort }}
  cohort: "{{ $config.cohort }}"
  {{ end }}
  resourceGroups:
  {{- range $resourceGroup := $config.resourceGroups }}
  - coveredResources:
    {{- range $resource := $resourceGroup.coveredResources }}
    - {{ $resource }}
    {{- end }}
    flavors:
    {{- range $flavor, $flavorResource := $resourceGroup.flavors }}
    - name: "{{ $flavorResource.name }}"
      resources:
      {{- range $resource, $resourceQuota := $flavorResource.resources }}
      - name: "{{ $resourceQuota.name }}"
        nominalQuota: {{ $resourceQuota.nominalQuota }}
        {{- if $resourceQuota.borrowingLimit }}
        borrowingLimit: {{ $resourceQuota.borrowingLimit }}
        {{- end }}
        {{- if $resourceQuota.lendingLimit }}
        lendingLimit: {{ $resourceQuota.lendingLimit }}
        {{- end }}
      {{- end }}
    {{- end }}
  {{- end }}
---
{{ end }}
{{- end }}