 {{- if .Values.kueue }}
{{ range $flavor, $config := .Values.kueue.resourceFlavors }}
apiVersion: kueue.x-k8s.io/v1beta1
kind: ResourceFlavor
metadata:
  name: {{ $config.name }}
{{- if $config.nodeLabels}}
spec:
  nodeLabels:
{{ toYaml $config.nodeLabels | indent 4 }}
{{- end}}
---
{{ end }}
{{- end}}