kubernetesClusterDomain: cluster.local

# Default values for skaha.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

# Tell Kubernetes to spin up multiple instances.  Defaults to 1.
replicaCount: 1

# It's best to keep these set as such, unless you're willing to change these in several places.
skaha:
  namespace: skaha-system
skahaWorkload:
  namespace: skaha-workload

# Skaha web service deployment
deployment:
  hostname: myhost.example.com  # Change this!
  skaha:
    image: images.opencadc.org/platform/skaha:0.16.1
    imagePullPolicy: Always
    skahaTld: "/arc"
    maxUserSessions: "3"
    sessionExpiry: "345600"
    defaultQuotaGB: "10"

    # Space delimited list of allowed Image Registry hosts.  These hosts should match the hosts in the User Session images.
    registryHosts: "images.canfar.net"

    # The group name to verify users against for permission to use the Science Platform.
    usersGroup: "ivo://skao.int/gms?prototyping-groups/mini-src/platform-users"

    adminsGroup: "ivo://skao.int/gms?prototyping-groups/mini-src/platform-users"

    # Group for users to preempt headless jobs.
    headlessGroup: "ivo://skao.int/gms?prototyping-groups/mini-src/platform-users"

    # Array of groups allowed to set the logging level.  If none set, then nobody can change the log level.
    # loggingGroups:
    #   - "ivo://skao.int/gms?prototyping-groups/mini-src/platform-users"

    # The Resource ID of the Service that contains the Posix Mapping information
    posixMapperResourceID: "ivo://example.org/posix-mapper"

    # URI or URL of the OIDC (IAM) server.  Used to validate incoming tokens.
    oidcURI: https://ska-iam.stfc.ac.uk/

    # ID (URI) of the GMS Service.
    gmsID: ivo://skao.int/gms

    registryURL: https://spsrc27.iaa.csic.es/reg

    # Optionally set the DEBUG port.
    # extraEnv:
    # - name: CATALINA_OPTS
    #   value: "-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=0.0.0.0:5555"
    # - name: JAVA_OPTS
    #   value: "-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=0.0.0.0:5555"

    # Resources provided to the Skaha service.
    resources:
      requests:
        memory: "1Gi"
        cpu: "500m"
      limits:
        memory: "1Gi"
        cpu: "500m"

    # Uncomment to debug.  Requires options above as well as service port exposure below.
    # extraPorts:
    # - containerPort: 5555
    #   protocol: TCP

    # Optionally mount a custom CA certificate
    # extraVolumeMounts:
    # - mountPath: "/config/cacerts"
    #   name: cacert-volume

    # If the base names have changed, then change them here, otherwise leave them.
    priorityClassName: uber-user-preempt-high
    serviceAccountName: skaha

    # The IdentityManager class handling authentication.  This should generally be left alone
    identityManagerClass: org.opencadc.auth.StandardIdentityManager

    # Create the CA certificate volume to be mounted in extraVolumeMounts
    # extraVolumes:
    # - name: cacert-volume
    #   secret:
    #     defaultMode: 420
    #     secretName: skaha-cacert-secret

secrets:
  # Uncomment to enable local or self-signed CA certificates for your domain to be trusted.
  # skaha-cacert-secret:
  #   ca.crt: <base64 encoded CA crt>

# Exposed extra ports.  Uncomment the java-debug port to expose and debug issues.
# service:
#   skaha:
#     extraPorts:
  #   - port: 5555
  #     protocol: TCP
  #     name: java-debug

# Set these appropriately to match your Persistent Volume labels.
storage:
  service:
    spec:
      # YAML for service mounted storage.
      # Example is the persistentVolumeClaim below.  Do not uncomment this
      # or Helm will use it as the default, even if a different spec
      # is specified.
      # persistentVolumeClaim:
      #   claimName: skaha-pvc
