bases:
- ../../../base/arc
namespace: skaha-system
patchesStrategicMerge:
- arc-tomcat-deployment.yaml
- arc-sshd-deployment.yaml
- arc-ingress.yaml
configMapGenerator:
- name: arc-config
  behavior: merge
  files:
  - config/cadc-registry.properties
  - config/catalina.properties
  - config/cavern.properties
generatorOptions:
 disableNameSuffixHash: true
