#!/bin/bash

UNAME=$1
SESSIONID=$2

echo "Running notebook session $SESSIONID for user $UNAME"

echo "Adding user to users group"
usermod -a -G users $UNAME
echo "Done"

echo "Running notebook"

#su -m -s /bin/bash -c 'export JUPYTER_TOKEN=$SESSIONID; export PATH=$PATH:/opt/conda/bin; echo $PATH; start-notebook.sh --NotebookApp.base_url=notebook/$SESSIONID' $UNAME

#su -m -s /bin/bash -c 'export JUPYTER_TOKEN=$SESSIONID; export PATH=$PATH:/opt/conda/bin; echo $PATH; start-notebook.sh --NotebookApp.base_url=notebook/$SESSIONID --NotebookApp.notebook_dir=/cavern' $UNAME

#su -m -s /bin/bash -c 'export JUPYTER_TOKEN=$SESSIONID; export JUPYTER_CONFIG_DIR=/home/jovyan; export JUPYTER_PATH=/home/jovyan; export PATH=$PATH:/opt/conda/bin; echo $PATH; start-notebook.sh --NotebookApp.base_url=notebook/$SESSIONID --NotebookApp.notebook_dir=/cavern' $UNAME

#su -m -s /bin/bash -c 'export JUPYTER_TOKEN=$SESSIONID; export JUPYTER_CONFIG_DIR=/home/jovyan; export JUPYTER_PATH=/home/jovyan; export PATH=$PATH:/opt/conda/bin; jupyter --paths' 

sudo SESSIONID=$SESSIONID su -s /bin/bash -c 'export HOME=/home/jovyan; echo "HOME: $HOME"; echo "SESSIONID: $SESSIONID"; export JUPYTER_TOKEN=$SESSIONID; export JUPYTER_CONFIG_DIR=/home/jovyan; export JUPYTER_PATH=/home/jovyan; export PATH=$PATH:/opt/conda/bin; start-notebook.sh --NotebookApp.base_url=notebook/$SESSIONID --NotebookApp.notebook_dir=/cavern --NotebookApp.allow_origin="*"' $UNAME

echo "Exiting"

