#!/bin/bash

set -e

### Give the SSSD container time to initialize
sleep 10

SELF=add-project
USAGE_MESSAGE="Usage: add-project <project-dir-name> <project-dir-owner-uid> <group-gid> <read-only | read-write> <quota in GB> <project-dir-base>"

TS=$(date)
echo "$TS $SELF START"

if [ -z "$6" ]
  then
    echo "${USAGE_MESSAGE}"
    exit 2
fi
PROJECT=$1
OWNER_UID=$2
GRANT_GID=$3
ACCESS_ARG=$4
QUOTA=$5
PROJECTS_BASE_DIR=$6
ACCESS=""
MODE=""

if [ $ACCESS_ARG == "read-only" ]
  then
    ACCESS="r-x"
    MODE="750"
elif [ $ACCESS_ARG == "read-write" ]
  then
    ACCESS="rwx"
    MODE="770"
else
  echo "${USAGE_MESSAGE}"
  exit 2
fi

if [ ! -d $PROJECTS_BASE_DIR ]
  then
  echo "${PROJECTS_BASE_DIR} does not exist."
  exit 2
fi

PROJECTDIR="$PROJECTS_BASE_DIR/$PROJECT"

if [ -d $PROJECTDIR ]
  then
  echo "Project $PROJECT already exists."
  exit 2
fi

echo "Creating project $PROJECT"
echo -n "  Creating project dir $PROJECTDIR..."
mkdir $PROJECTDIR
echo " Done"
echo -n "  Setting permissions to $ACCESS for group $GRANT_GID"
chown $OWNER_UID:$OWNER_UID $PROJECTDIR
chmod $MODE $PROJECTDIR
setfacl -d -m group:$GRANT_GID:$ACCESS $PROJECTDIR
setfacl -m group:$GRANT_GID:$ACCESS $PROJECTDIR
echo -n "  Setting quota to ${QUOTA}G"
setfattr -n ceph.quota.max_bytes -v ${QUOTA}000000000 $PROJECTDIR
setfattr -n user.ivo://ivoa.net/vospace/core#quota -v ${QUOTA}000000000 $PROJECTDIR
echo " Done"

TS=$(date)
echo "$TS $SELF DONE"
