# Example Persistent Volume declaration for the Skaha web service to use.  The labels to match on is configurable.  This is for LOCAL storage 
# only for the services (i.e. running on a laptop), and will not be installed by default, but could be used on a new Cluster.
# In the values file for Skaha, the name of the PersistentVolumeClaim below will be referenced.
{{- if .Values.storage.session.create }}
apiVersion: v1
kind: PersistentVolume
metadata:
  name: science-platform-volume  # Name is irrelevant
  labels:
{{- toYaml .Values.storage.session.labels | nindent 4 }}
spec:
  capacity:
    storage: 10Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Delete
  storageClassName: local-storage
  local:
    path: /data/skaha-workload
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - docker-desktop  # Single node docker-desktop for macOS and Windows.
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  annotations:
    helm.sh/resource-policy: keep
  name: {{ .Values.skahaWorkload.namespace }}-cavern-pvc
  namespace: {{ .Values.skahaWorkload.namespace }}
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
  selector:
    matchLabels:
{{- toYaml .Values.storage.session.labels | nindent 6 }}
{{ end }}