# Ensure the X-Forwarded-Tls-Client-Cert header is being set.
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: traefik-passtlsclientcert
  namespace: {{ .Release.Namespace }}
spec:
  passTLSClientCert:
    pem: true
---
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: traefik-header-transform
  namespace: {{ .Release.Namespace }}
spec:
  plugin:
    htransformation:
      Rules:
        - Header: X-Forwarded-Tls-Client-Cert
          Name: Client certificate header rename
          Type: Rename
          Value: X-Client-Certificate
---
apiVersion: traefik.containo.us/v1alpha1
kind: TLSOption
metadata:
  name: traefik-client-cert-option
  namespace: {{ .Release.Namespace }}
spec:
  clientAuth:
    clientAuthType: RequestClientCert
